# Site
name: 'Inequality from Above'
description: 'Results from Project Measuring Inequality from above.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: "https://inequalityfromabove.github.io/" # the base hostname & protocol for your site
disqus: ''
email: 'wowthemesnet@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    sal:
      name:           JC
      site:           https://jcmunozmora.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "..."
      email:          jmunozm1@eafit.edu.co
      twitter:        https://twitter.com/jcmunozmora

    jane:
      name:           Ramon
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "..."
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
